# frozen_string_literal: true

bjcp_styles = [
  { name: 'Standard American Beer', bjcp_category: '1' },
  { name: 'American Light Lager', bjcp_category: '1A' },
  { name: 'American Lager', bjcp_category: '1B' },
  { name: 'Cream Ale', bjcp_category: '1C' },
  { name: 'American Wheat Beer', bjcp_category: '1D' },
  { name: 'International Lager', bjcp_category: '2' },
  { name: 'International Pale Lager', bjcp_category: '2A' },
  { name: 'International Amber Lager', bjcp_category: '2B' },
  { name: 'International Dark Lager', bjcp_category: '2C' },
  { name: 'Czech Lager', bjcp_category: '3' },
  { name: 'Czech Pale Lager', bjcp_category: '3A' },
  { name: 'Czech Premium Pale Lager', bjcp_category: '3B' },
  { name: 'Czech Amber Lager', bjcp_category: '3C' },
  { name: 'Czech Dark Lager', bjcp_category: '3D' },
  { name: 'Pale Malty European Lager', bjcp_category: '4' },
  { name: 'Munich Helles', bjcp_category: '4A' },
  { name: 'Festbier', bjcp_category: '4B' },
  { name: 'Helles Bock', bjcp_category: '4C' },
  { name: 'Pale Bitter European Beer', bjcp_category: '5' },
  { name: 'German Leichtbier', bjcp_category: '5A' },
  { name: 'Kölsch', bjcp_category: '5B' },
  { name: 'German Helles Exportbier', bjcp_category: '5C' },
  { name: 'German Pils', bjcp_category: '5D' },
  { name: 'Amber Malty European Lager', bjcp_category: '6' },
  { name: 'Märzen', bjcp_category: '6A' },
  { name: 'Rauchbier', bjcp_category: '6B' },
  { name: 'Dunkles Bock', bjcp_category: '6C' },
  { name: 'Amber Bitter European Beer', bjcp_category: '7' },
  { name: 'Vienna Lager', bjcp_category: '7A' },
  { name: 'Altbier', bjcp_category: '7B' },
  { name: 'Dark European Lager', bjcp_category: '8' },
  { name: 'Munich Dunkel', bjcp_category: '8A' },
  { name: 'Schwarzbier', bjcp_category: '8B' },
  { name: 'Strong European Beer', bjcp_category: '9' },
  { name: 'Doppelbock', bjcp_category: '9A' },
  { name: 'Eisbock', bjcp_category: '9B' },
  { name: 'Baltic Porter', bjcp_category: '9C' },
  { name: 'German Wheat Beer', bjcp_category: '10' },
  { name: 'Weissbier', bjcp_category: '10A' },
  { name: 'Dunkles Weissbier', bjcp_category: '10B' },
  { name: 'Weizenbock', bjcp_category: '10C' },
  { name: 'British Bitter', bjcp_category: '11' },
  { name: 'Ordinary Bitter', bjcp_category: '11A' },
  { name: 'Best Bitter', bjcp_category: '11B' },
  { name: 'Strong Bitter', bjcp_category: '11C' },
  { name: 'Pale Commonwealth Beer', bjcp_category: '12' },
  { name: 'British Golden Ale', bjcp_category: '12A' },
  { name: 'Australian Sparkling Ale', bjcp_category: '12B' },
  { name: 'English IPA', bjcp_category: '12C' },
  { name: 'Brown British Beer', bjcp_category: '13' },
  { name: 'Dark Mild', bjcp_category: '13A' },
  { name: 'British Brown Ale', bjcp_category: '13B' },
  { name: 'English Porter', bjcp_category: '13C' },
  { name: 'Scottish Ale', bjcp_category: '14' },
  { name: 'Scottish Light', bjcp_category: '14A' },
  { name: 'Scottish Heavy', bjcp_category: '14B' },
  { name: 'Scottish Export', bjcp_category: '14C' },
  { name: 'Irish Beer', bjcp_category: '15' },
  { name: 'Irish Red Ale', bjcp_category: '15A' },
  { name: 'Irish Stout', bjcp_category: '15B' },
  { name: 'Irish Extra Stout', bjcp_category: '15C' },
  { name: 'Dark British Beer', bjcp_category: '16' },
  { name: 'Sweet Stout', bjcp_category: '16A' },
  { name: 'Oatmeal Stout', bjcp_category: '16B' },
  { name: 'Tropical Stout', bjcp_category: '16C' },
  { name: 'Foreign Extra Stout', bjcp_category: '16D' },
  { name: 'Strong British Ale', bjcp_category: '17' },
  { name: 'British Strong Ale', bjcp_category: '17A' },
  { name: 'Old Ale', bjcp_category: '17B' },
  { name: 'Wee Heavy', bjcp_category: '17C' },
  { name: 'English Barleywine', bjcp_category: '17D' },
  { name: 'Pale American Ale', bjcp_category: '18' },
  { name: 'Blonde Ale', bjcp_category: '18A' },
  { name: 'American Pale Ale', bjcp_category: '18B' },
  { name: 'Amber and Brown American Beer', bjcp_category: '19' },
  { name: 'American Amber Ale', bjcp_category: '19A' },
  { name: 'California Common', bjcp_category: '19B' },
  { name: 'American Brown Ale', bjcp_category: '19C' },
  { name: 'American Porter and Stout', bjcp_category: '20' },
  { name: 'American Porter', bjcp_category: '20A' },
  { name: 'American Stout', bjcp_category: '20B' },
  { name: 'Imperial Stout', bjcp_category: '20C' },
  { name: 'IPA', bjcp_category: '21' },
  { name: 'American IPA', bjcp_category: '21A' },
  { name: 'Specialty IPA', bjcp_category: '21B' },
  { name: 'Belgian IPA', bjcp_category: 'Specialty' },
  { name: 'Black IPA', bjcp_category: 'Specialty' },
  { name: 'Brown IPA', bjcp_category: 'Specialty' },
  { name: 'Red IPA', bjcp_category: 'Specialty' },
  { name: 'Rye IPA', bjcp_category: 'Specialty' },
  { name: 'White IPA', bjcp_category: 'Specialty' },
  { name: 'Brut IPA', bjcp_category: 'Specialty' },
  { name: 'Hazy IPA', bjcp_category: '21C' },
  { name: 'Strong American Ale', bjcp_category: '22' },
  { name: 'Double IPA', bjcp_category: '22A' },
  { name: 'American Strong Ale', bjcp_category: '22B' },
  { name: 'American Barleywine', bjcp_category: '22C' },
  { name: 'Wheatwine', bjcp_category: '22D' },
  { name: 'European Sour Ale', bjcp_category: '23' },
  { name: 'Berliner Weisse', bjcp_category: '23A' },
  { name: 'Flanders Red Ale', bjcp_category: '23B' },
  { name: 'Oud Bruin', bjcp_category: '23C' },
  { name: 'Lambic', bjcp_category: '23D' },
  { name: 'Gueuze', bjcp_category: '23E' },
  { name: 'Fruit Lambic', bjcp_category: '23F' },
  { name: 'Gose', bjcp_category: '23G' },
  { name: 'Belgian Ale', bjcp_category: '24' },
  { name: 'Witbier', bjcp_category: '24A' },
  { name: 'Belgian Pale Ale', bjcp_category: '24B' },
  { name: 'Bière de Garde', bjcp_category: '24C' },
  { name: 'Strong Belgian Ale', bjcp_category: '25' },
  { name: 'Belgian Blond Ale', bjcp_category: '25A' },
  { name: 'Saison', bjcp_category: '25B' },
  { name: 'Belgian Golden Strong Ale', bjcp_category: '25C' },
  { name: 'Monastic Ale', bjcp_category: '26' },
  { name: 'Belgian Single', bjcp_category: '26A' },
  { name: 'Belgian Dubbel', bjcp_category: '26B' },
  { name: 'Belgian Tripel', bjcp_category: '26C' },
  { name: 'Belgian Dark Strong Ale', bjcp_category: '26D' },
  { name: 'Historical Beer', bjcp_category: '27' },
  { name: 'Kellerbier', bjcp_category: 'Historical' },
  { name: 'Kentucky Common', bjcp_category: 'Historical' },
  { name: 'Lichtenhainer', bjcp_category: 'Historical' },
  { name: 'London Brown Ale', bjcp_category: 'Historical' },
  { name: 'Piwo Grodziskie', bjcp_category: 'Historical' },
  { name: 'Pre-Prohibition Lager', bjcp_category: 'Historical' },
  { name: 'Pre-Prohibition Porter', bjcp_category: 'Historical' },
  { name: 'Roggenbier', bjcp_category: 'Historical' },
  { name: 'Sahti', bjcp_category: 'Historical' },
  { name: 'American Wild Ale', bjcp_category: '28' },
  { name: 'Brett Beer', bjcp_category: '28A' },
  { name: 'Mixed-Fermentation Sour Beer', bjcp_category: '28B' },
  { name: 'Wild Specialty Beer', bjcp_category: '28C' },
  { name: 'Straight Sour Beer', bjcp_category: '28D' },
  { name: 'Fruit Beer', bjcp_category: '29' },
  { name: 'Fruit Beer', bjcp_category: '29A' },
  { name: 'Fruit and Spice Beer', bjcp_category: '29B' },
  { name: 'Specialty Fruit Beer', bjcp_category: '29C' },
  { name: 'Grape Ale', bjcp_category: '29D' },
  { name: 'Spiced Beer', bjcp_category: '30' },
  { name: 'Spice, Herb, or Vegetable Beer', bjcp_category: '30A' },
  { name: 'Autumn Seasonal Beer', bjcp_category: '30B' },
  { name: 'Winter Seasonal Beer', bjcp_category: '30C' },
  { name: 'Specialty Spice Beer', bjcp_category: '30D' },
  { name: 'Alternative Fermentables Beer', bjcp_category: '31' },
  { name: 'Alternative Grain Beer', bjcp_category: '31A' },
  { name: 'Alternative Sugar Beer', bjcp_category: '31B' },
  { name: 'Smoked Beer', bjcp_category: '32' },
  { name: 'Classic Style Smoked Beer', bjcp_category: '32A' },
  { name: 'Specialty Smoked Beer', bjcp_category: '32B' },
  { name: 'Wood Beer', bjcp_category: '33' },
  { name: 'Wood-Aged Beer', bjcp_category: '33A' },
  { name: 'Specialty Wood-Aged Beer', bjcp_category: '33B' },
  { name: 'Specialty Beer', bjcp_category: '34' },
  { name: 'Commercial Specialty Beer', bjcp_category: '34A' },
  { name: 'Mixed-Style Beer', bjcp_category: '34B' },
  { name: 'Experimental Beer', bjcp_category: '34C' }
]

bjcp_styles.each do |style|
  Style.create!(name: style[:name], bjcp_category: style[:bjcp_category])
end
